services:
  db:
    image: postgres:16-alpine
    container_name: trufiq_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: trufi
      POSTGRES_PASSWORD: trufi
      POSTGRES_DB: trufiq
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
