"""initial_schema

Revision ID: 0001
Revises: 
Create Date: 2026-04-03 19:55:44.569343

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('hashed_password', sa.String(length=200), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('plots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('polygon', sa.String(length=100), nullable=False),
    sa.Column('plot_num', sa.String(length=100), nullable=False),
    sa.Column('cadastral_ref', sa.String(length=100), nullable=False),
    sa.Column('hydrant', sa.String(length=100), nullable=False),
    sa.Column('sector', sa.String(length=100), nullable=False),
    sa.Column('num_plants', sa.Integer(), nullable=False),
    sa.Column('planting_date', sa.Date(), nullable=False),
    sa.Column('area_ha', sa.Float(), nullable=True),
    sa.Column('production_start', sa.Date(), nullable=True),
    sa.Column('percentage', sa.Float(), nullable=False),
    sa.Column('has_irrigation', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plots_id'), 'plots', ['id'], unique=False)
    op.create_index(op.f('ix_plots_user_id'), 'plots', ['user_id'], unique=False)
    op.create_table('expenses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('person', sa.String(length=200), nullable=False),
    sa.Column('plot_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('receipt_filename', sa.String(length=255), nullable=True),
    sa.Column('receipt_data', sa.LargeBinary(), nullable=True),
    sa.Column('receipt_content_type', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['plot_id'], ['plots.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_expenses_date'), 'expenses', ['date'], unique=False)
    op.create_index(op.f('ix_expenses_id'), 'expenses', ['id'], unique=False)
    op.create_index(op.f('ix_expenses_plot_id'), 'expenses', ['plot_id'], unique=False)
    op.create_index(op.f('ix_expenses_user_id'), 'expenses', ['user_id'], unique=False)
    op.create_table('incomes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('plot_id', sa.Integer(), nullable=True),
    sa.Column('amount_kg', sa.Float(), nullable=False),
    sa.Column('category', sa.String(length=200), nullable=False),
    sa.Column('euros_per_kg', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['plot_id'], ['plots.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incomes_date'), 'incomes', ['date'], unique=False)
    op.create_index(op.f('ix_incomes_id'), 'incomes', ['id'], unique=False)
    op.create_index(op.f('ix_incomes_plot_id'), 'incomes', ['plot_id'], unique=False)
    op.create_index(op.f('ix_incomes_user_id'), 'incomes', ['user_id'], unique=False)
    op.create_table('irrigation_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('plot_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('water_m3', sa.Float(), nullable=False),
    sa.Column('expense_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['expense_id'], ['expenses.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['plot_id'], ['plots.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_irrigation_records_date'), 'irrigation_records', ['date'], unique=False)
    op.create_index(op.f('ix_irrigation_records_expense_id'), 'irrigation_records', ['expense_id'], unique=False)
    op.create_index(op.f('ix_irrigation_records_id'), 'irrigation_records', ['id'], unique=False)
    op.create_index(op.f('ix_irrigation_records_plot_id'), 'irrigation_records', ['plot_id'], unique=False)
    op.create_index(op.f('ix_irrigation_records_user_id'), 'irrigation_records', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_irrigation_records_user_id'), table_name='irrigation_records')
    op.drop_index(op.f('ix_irrigation_records_plot_id'), table_name='irrigation_records')
    op.drop_index(op.f('ix_irrigation_records_id'), table_name='irrigation_records')
    op.drop_index(op.f('ix_irrigation_records_expense_id'), table_name='irrigation_records')
    op.drop_index(op.f('ix_irrigation_records_date'), table_name='irrigation_records')
    op.drop_table('irrigation_records')
    op.drop_index(op.f('ix_incomes_user_id'), table_name='incomes')
    op.drop_index(op.f('ix_incomes_plot_id'), table_name='incomes')
    op.drop_index(op.f('ix_incomes_id'), table_name='incomes')
    op.drop_index(op.f('ix_incomes_date'), table_name='incomes')
    op.drop_table('incomes')
    op.drop_index(op.f('ix_expenses_user_id'), table_name='expenses')
    op.drop_index(op.f('ix_expenses_plot_id'), table_name='expenses')
    op.drop_index(op.f('ix_expenses_id'), table_name='expenses')
    op.drop_index(op.f('ix_expenses_date'), table_name='expenses')
    op.drop_table('expenses')
    op.drop_index(op.f('ix_plots_user_id'), table_name='plots')
    op.drop_index(op.f('ix_plots_id'), table_name='plots')
    op.drop_table('plots')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
